[package]
version = "0.1.0"
name = "bindb"
authors = ["afaal"]
edition = "2018"

[dependencies]
memmap = "0.7.0"
nix    = "0.20.0"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "benchmark"
harness = false